[riak_servers]
manaslu5 ansible_host=manaslu5.uwyo.edu
manaslu6 ansible_host=manaslu6.uwyo.edu
manaslu7 ansible_host=manaslu7.uwyo.edu
manaslu8 ansible_host=manaslu8.uwyo.edu
manaslu9 ansible_host=manaslu9.uwyo.edu


[riak_clients]
manaslu1 ansible_host=manaslu1.uwyo.edu
manaslu2 ansible_host=manaslu2.uwyo.edu
manaslu3 ansible_host=manaslu3.uwyo.edu
manaslu4 ansible_host=manaslu4.uwyo.edu
manaslu10 ansible_host=manaslu10.uwyo.edu
manaslu11 ansible_host=manaslu11.uwyo.edu
manaslu12 ansible_host=manaslu12.uwyo.edu
yangra1 ansible_host=yangra1.uwyo.edu
yangra2 ansible_host=yangra2.uwyo.edu
yangra3 ansible_host=yangra3.uwyo.edu
yangra4 ansible_host=yangra4.uwyo.edu
yangra5 ansible_host=yangra5.uwyo.edu
yangra6 ansible_host=yangra6.uwyo.edu
yangra7 ansible_host=yangra7.uwyo.edu
yangra8 ansible_host=yangra8.uwyo.edu
yangra9 ansible_host=yangra9.uwyo.edu
yangra10 ansible_host=yangra10.uwyo.edu
yangra11 ansible_host=yangra11.uwyo.edu


[all:vars]
ansible_user=agaru
ansible_ssh_private_key_file=~/.ssh/id_ed25519
