[riak_servers]
manaslu5 ansible_host=manaslu5.uwyo.edu



[riak_clients]
manaslu1 ansible_host=manaslu1.uwyo.edu
manaslu2 ansible_host=manaslu2.uwyo.edu



[all:vars]
ansible_user=agaru
ansible_ssh_private_key_file=~/.ssh/id_ed25519
