---
- name: Execute experiments on the clients
  hosts: riak_clients
  remote_user: agaru

  vars:
    deploy_path: /opt/client_app
    bucket_n_val: 3
    bucket_r_val: quorom
    bucket_w_val: quorom
    bucket_dw_val: quorom

  tasks:
    - name: Set client-specific variables
      set_fact:
        client_id: "{{ groups['riak_clients'].index(inventory_hostname) }}"
        num_clients: "{{ groups['riak_clients'] | length }}"
        riak_servers: "{{ groups['riak_servers'] | join(';') }}"

    - name: Generate job date
      set_fact:
        job_date: "{{ lookup('pipe', 'date +%Y_%m_%d') }}"
      run_once: true
      delegate_to: localhost

    - name: Generate unique client job ID
      set_fact:
        client_job_id: "{{ lookup('pipe', 'date +%H_%M') }}_{{ 90000 | random(10000) }}"
      run_once: true
      delegate_to: localhost
    
    - name: Share client_job_id with all hosts
      set_fact:
        job_date: "{{ hostvars[groups['riak_clients'][0]].job_date }}"
        client_job_id: "{{ hostvars[groups['riak_clients'][0]].client_job_id }}"

    - debug:
        var: client_job_id

    - name: Copy client files
      become: yes
      synchronize:
        src: python_client/
        dest: "{{ deploy_path }}/"
        recursive: yes
        delete: no
    
    - name: Make run_nohup.sh executable
      file:
        path: "{{ deploy_path }}/run_nohup.sh"
        mode: '0755'
    
    - name: Make nohup_commands.sh executable
      file:
        path: "{{ deploy_path }}/nohup_commands.sh"
        mode: '0755'

    - name: Ensure log directory exists in the host
      file:
        path: "ansible_logs/{{ job_date }}"
        state: directory
        mode: '0755'
      run_once: true
      delegate_to: localhost

    - name: Prepare database
      shell: python3 prepare_database.py --graph-name "{{graph}}" > ../ansible_logs/{{ job_date }}/{{ client_job_id }}.log 2>&1
      environment:
        RIAK_SERVER_URLS: "{{ riak_servers }}"
      run_once: true
      delegate_to: localhost
      args:
        chdir: "python_client/"

    - name: Update bucket properties
      command: curl -X PUT -H "Content-Type: application/json" -d "{\"props\":{\"n_val\":{{ bucket_n_val }}, \"r\":{{ bucket_r_val }}, \"w\":{{ bucket_w_val }}, \"dw\":{{bucket_dw_val}}}}" http://{{groups['riak_servers'][0]}}:8098/buckets/graph_coloring__{{graph}}/props
      run_once: true
      delegate_to: localhost

    - name: Sleep for 10 seconds
      pause:
        seconds: 10

    - name: Execute client application
      command: ./run_nohup.sh {{client_job_id}} {{graph}} {{client_id}} {{num_clients}}
      become: yes
      environment:
        RIAK_SERVER_URLS: "{{ riak_servers }}"
      args:
        chdir: "{{ deploy_path }}"